### ISSUE TITLE
Extension not working in VS2019

### ISSUE THREAD

**Issue by stephanemathis** [renestein/ConfigureAwaitEnforcer#7]
Hello, 

I've installed the extension in VS2019 but it does not seem to work. 
I never get an error when i'm missing the ConfigureAwait call.

Here is an exemple in a dummy project.
![image](https://user-images.githubusercontent.com/2813530/140504344-f04974c4-de7d-4659-aaef-c14d1f42f5fc.png)

Is there something i'm missing ?
I've also tried to install the nuget in addition to the extension but it did not work any better.

Thanks in advance,
Stéphane

**Comment by renestein** [comment]
Hi @stephanemathis ,
thanks for the report.
Its weird, because VS 2019 (version 16.11.3) works
![awaitSimple](https://user-images.githubusercontent.com/386151/140508427-c4e19460-69f9-47d9-99a1-c816683f731b.gif)
.
Nuget is not needed. Do you have the last version of the extension? Was the extension installed from the Visual Studio?
Did you try to reinstall the extension?

**Comment by stephanemathis** [comment]
Thanks for your response !
I tried to uninstall it and re-install it from the Extension window in Visual Studio but it still does not work.

I have the version 16.7.7 of Visual Studio. I'll try to update VS.

**Comment by stephanemathis** [comment]
With the latest VS version it works great. Thanks !

**Comment by renestein** [comment]
Thanks for letting me know! This extension works without any issues in older VS versions. I have a suspicion that your VS installation was broken and the update "somehow" fixed it.
